apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: demo
spec:
  containers:
    - name: ngnix
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /data/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-pvc
