apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: demo
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  accessModes: 
    - ReadWriteOnce
