apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: add-tls
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef: 
    name: ha-postgres
  tls:
    sslMode: verify-ca
    clientAuthMode: cert
    issuerRef:
      name: pg-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    certificates:
      - alias: client
        subject:
          organizations:
            - postgres
        dnsNames:
          - localhost
        ipAddresses:
          - 127.0.0.1
      - alias: server
        subject:
          organizations:
            - postgres
        dnsNames:
          - localhost
        ipAddresses:
          - 127.0.0.1