apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: postgres-daemonset
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image:  ghcr.io/kubedb/postgres-init:0.11.0
        imagePullPolicy: Always   
