apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: monitor-postgres
  namespace: demo
spec:
  podTemplate:
    spec:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 70 # 999 for mongo
        seccompProfile:
          type: RuntimeDefault
  version: "14.6"
  replicas: 3
  coordinator:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  storageType: Durable
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io/builtin
    prometheus:
     exporter:
       securityContext:
         allowPrivilegeEscalation: false
         capabilities:
           drop:
           - ALL
         runAsNonRoot: true
         runAsUser: 999
         seccompProfile:
           type: RuntimeDefault
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
