apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: arb-postgres
  namespace: demo
spec:
  podTemplate:
    spec:
      containerSecurityContext:
        capabilities:
          add:
          - IPS_LOCK
          - SYS_RESOURCE
  version: "14.1"
  replicas: 3
  storageType: Durable
  terminationPolicy: WipeOut
  storage:
    storageClassName: "linode-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
