apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pg-vol-exp
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: ha-postgres
  volumeExpansion:
    mode: Online
   # postgres: 11Gi
    arbiter: 12Gi
