apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: storage
  namespace: demo
stringData:
  AWS_ACCESS_KEY_ID: "***226CX"
  AWS_SECRET_ACCESS_KEY: "****tAjj3lp"
  AWS_ENDPOINT: https://ap-south-1.linodeobjects.com